### ISSUE TITLE
[REMOTE] Allow users to dynamically choose which context(cluster) to use for each workflow

### ISSUE THREAD

**Issue by cbmckni** [SciDAS/nextflow-api#16]
Users should be able to choose which context(cluster) they want to use for each workflow. 

On workflow creation, user selects from available contexts via a dropdown.

On launch, Nextflow-API switches to correct context to load data and launch workflow.

Available contexts can be pulled by using `kubectl config get contexts', then parsed into HTML select.

At the beginning of launch, switch to correct context with 'kubectl config use-context <context>`

"context" field will need to be added to workflow metadata.

**Comment by bentsherman** [comment]
The conclusion of this effort was that it cannot be done because users cannot virtualize their credentials via service account, which is a fundamental limitation of Kubernetes. Also, we decided we don't need to implement authentication since a Nextflow-API instance will be tied to a single user and a single kubernetes cluster. Therefore we will close this issue.
