### ISSUE TITLE
API calls required for Tripal integration

### ISSUE THREAD

**Issue by 4ctrl-alt-del** [SciDAS/nextflow-api#9]
After reviewing the code I think the following things still need to be added to allow Stephen to fully integrate this with Tripal:

* A status call that returns at least: submitted, running, failed, waiting, complete (This may already exist but I wasn't able to find any status API call in server.py even though it is mentioned in the README)
* Permanent storage of output files and the ability to download individual output files because they cannot be stored on tripal servers
* Checking status of the cluster: available or not available

**Comment by 4ctrl-alt-del** [comment]
Also just to be sure I am correct, the URLs for the software used by nextflow is provided in the nextflow.config file that is uploaded correct?

**Comment by bentsherman** [comment]
I have updated the README to properly reflect the current API. There's no longer a specific status endpoint because it's included in the `GET /api/workflows/{id}` endpoint, which fetches the entire workflow metadata.

The API creates a tarball of the output data so that it can be downloaded in one go, and as long as you don't delete the workflow, the data will persist. Also if you rerun the same workflow then the previous output data will be overwritten. We could probably add an endpoint for downloading individual files.

As for the cluster status, I mean... if you can deploy the nextflow API then the cluster is available so it's sort of a constant as far as I can tell.

I'm not sure what URLs you're talking about? The nextflow.config file does contain the Docker images which are pulled from DockerHub.

**Comment by 4ctrl-alt-del** [comment]
By URLs I mean the github URL used to fetch the software that nextflow actually executes.

**Comment by bentsherman** [comment]
Right, the name of the nextflow pipeline. That is provided in the `POST /api/workflows` endpoint for creating a workflow run. You put the pipeline name in the request body.

**Comment by bentsherman** [comment]
You can look at the CLI scripts too in the `cli` folder, they give a minimal example of how the API works.

**Comment by bentsherman** [comment]
Okay this feature has been implemented as part of the `download` API endpoint. If you provide a `path` argument in the query string then it will download that particular file, otherwise it will give you the output data archive. For example:
```
/api/workflows/{id}/download?path=output/workflow.log
```

Regarding your question @4ctrl-alt-del, yes you can just leave the workflow instance as it will not use compute resources if it's not running, only storage.
